# Install script for directory: /home/jarvis/Documents/freecad-source/src/Gui/Stylesheets

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Install shared libraries without execute permission?
if(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  set(CMAKE_INSTALL_SO_NO_EXE "1")
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

# Set default install directory permissions.
if(NOT DEFINED CMAKE_OBJDUMP)
  set(CMAKE_OBJDUMP "/usr/bin/objdump")
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/Gui/Stylesheets" TYPE FILE FILES
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/FreeCAD Dark.qss"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/FreeCAD Light.qss"
    )
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/Gui/Stylesheets/overlay" TYPE FILE FILES
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/overlay/Dark Theme + Dark Background.qss"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/overlay/Dark Theme + Light Background.qss"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/overlay/Light Theme + Dark Background.qss"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/overlay/Light Theme + Light Background.qss"
    )
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/Gui/Stylesheets/overlay/icons" TYPE FILE FILES
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/overlay/icons/autohide.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/overlay/icons/autohide_light.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/overlay/icons/autohide_lighter.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/overlay/icons/autohide_lightgray.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/overlay/icons/close.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/overlay/icons/close_light.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/overlay/icons/close_lighter.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/overlay/icons/close_red.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/overlay/icons/edithide.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/overlay/icons/edithide_light.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/overlay/icons/edithide_lighter.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/overlay/icons/edithide_lightgray.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/overlay/icons/editshow.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/overlay/icons/editshow_light.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/overlay/icons/editshow_lighter.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/overlay/icons/editshow_lightgray.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/overlay/icons/float.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/overlay/icons/float_light.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/overlay/icons/float_lighter.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/overlay/icons/mode.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/overlay/icons/mode_light.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/overlay/icons/mode_lighter.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/overlay/icons/mode_lightgray.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/overlay/icons/overlay.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/overlay/icons/overlay_light.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/overlay/icons/overlay_lighter.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/overlay/icons/taskshow.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/overlay/icons/taskshow_light.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/overlay/icons/taskshow_lighter.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/overlay/icons/taskshow_lightgray.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/overlay/icons/transparent.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/overlay/icons/transparent_light.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/overlay/icons/transparent_lighter.svg"
    )
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/Gui/Stylesheets/images_dark-light" TYPE FILE FILES
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/Hmovetoolbar_dark.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/Hmovetoolbar_light.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/Hsepartoolbar_dark.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/Hsepartoolbar_light.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/Vmovetoolbar_dark.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/Vmovetoolbar_light.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/Vsepartoolbar_dark.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/Vsepartoolbar_light.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/background_freecad.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/background_freecad_dark.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/background_freecad_light.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/branch_end_closed_dark.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/branch_end_closed_light.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/branch_end_dark.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/branch_end_light.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/branch_end_open_dark.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/branch_end_open_light.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/branch_more_closed_dark.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/branch_more_closed_light.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/branch_more_dark.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/branch_more_light.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/branch_more_open_dark.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/branch_more_open_light.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/branch_vline_dark.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/branch_vline_light.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/check_dark.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/check_dark_disabled.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/check_light.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/check_light_disabled.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/checkbox_checked_disabled.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/checkbox_dark.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/checkbox_dark_hover.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/checkbox_indeterminate_dark.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/checkbox_indeterminate_light.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/checkbox_light.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/checkbox_light_hover.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/checkbox_unchecked_dark.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/checkbox_unchecked_disabled.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/checkbox_unchecked_hover_dark.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/checkbox_unchecked_hover_light.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/checkbox_unchecked_light.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/close_dark.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/close_light.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/close_red.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/down_arrow_dark.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/down_arrow_darker.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/down_arrow_disabled_dark.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/down_arrow_disabled_light.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/down_arrow_light.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/down_arrow_lighter.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/left_arrow_dark.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/left_arrow_darker.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/left_arrow_disabled_dark.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/left_arrow_disabled_light.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/left_arrow_light.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/left_arrow_lighter.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/more_arrow_dark.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/more_arrow_light.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/more_dark.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/more_light.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/radiobutton_dark.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/radiobutton_light.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/right_arrow_dark.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/right_arrow_darker.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/right_arrow_disabled_dark.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/right_arrow_disabled_light.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/right_arrow_light.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/right_arrow_lighter.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/sizegrip_dark.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/sizegrip_light.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/splitter_horizontal_dark.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/splitter_horizontal_light.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/splitter_vertical_dark.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/splitter_vertical_light.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/transparent.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/undock_blue.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/undock_dark.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/undock_light.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/up-down_arrow_dark.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/up-down_arrow_darker.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/up-down_arrow_disabled_dark.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/up-down_arrow_disabled_light.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/up-down_arrow_light.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/up-down_arrow_lighter.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/up_arrow_dark.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/up_arrow_darker.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/up_arrow_disabled_dark.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/up_arrow_disabled_light.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/up_arrow_light.svg"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_dark-light/up_arrow_lighter.svg"
    )
endif()

if(CMAKE_INSTALL_COMPONENT STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/share/Gui/Stylesheets/images_classic" TYPE FILE FILES
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Arrow-double-LeftRight-black.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Arrow-double-LeftRight-blue.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Arrow-double-LeftRight-darkgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Arrow-double-LeftRight-lightgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Arrow-double-LeftRight-white.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Arrow-double-UpDown-black.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Arrow-double-UpDown-blue.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Arrow-double-UpDown-darkgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Arrow-double-UpDown-lightgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Arrow-double-UpDown-white.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Arrow-down-black.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Arrow-down-blue.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Arrow-down-darkgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Arrow-down-lightgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Arrow-down-white.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Arrow-left-black.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Arrow-left-blue.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Arrow-left-darkgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Arrow-left-lightgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Arrow-left-white.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Arrow-leftDown-black.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Arrow-leftDown-blue.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Arrow-leftDown-darkgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Arrow-leftDown-lightgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Arrow-leftDown-white.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Arrow-right-black.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Arrow-right-blue.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Arrow-right-darkgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Arrow-right-lightgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Arrow-right-white.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Arrow-rightDown-black.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Arrow-rightDown-blue.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Arrow-rightDown-darkgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Arrow-rightDown-lightgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Arrow-rightDown-white.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Arrow-up-black.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Arrow-up-blue.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Arrow-up-darkgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Arrow-up-lightgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Arrow-up-white.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Close-DarkRed.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Close-lightgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Hmovetoolbar-black.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Hmovetoolbar-blue.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Hmovetoolbar-darkgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Hmovetoolbar-lightgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Hmovetoolbar-white.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Hsepartoolbar-black.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Hsepartoolbar-blue.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Hsepartoolbar-darkgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Hsepartoolbar-lightgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Hsepartoolbar-white.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Qsint_header_FoldOver_Blue-Blue.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Qsint_header_FoldOver_Blue-dark.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Qsint_header_FoldOver_Blue-light.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Qsint_header_Fold_Blue-Blue.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Qsint_header_Fold_Blue-dark.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Qsint_header_Fold_Blue-light.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Qsint_header_UnFoldOver_Blue-Blue.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Qsint_header_UnfoldOver_Blue-dark.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Qsint_header_UnfoldOver_Blue-light.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Qsint_header_Unfold_Blue-Blue.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Qsint_header_Unfold_Blue-dark.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Qsint_header_Unfold_Blue-light.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Qsint_header_fold_black.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Qsint_header_fold_darkgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Qsint_header_fold_lightgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Qsint_header_fold_white.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Qsint_header_unfold_black.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Qsint_header_unfold_darkgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Qsint_header_unfold_lightgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Qsint_header_unfold_white.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Radio-checked-black.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Radio-checked-blue.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Radio-checked-darkgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Radio-checked-lightgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Radio-checked-white.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Radio-unchecked-black.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Radio-unchecked-blue.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Radio-unchecked-darkgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Radio-unchecked-lightgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Radio-unchecked-white.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Vmovetoolbar-black.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Vmovetoolbar-blue.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Vmovetoolbar-darkgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Vmovetoolbar-lightgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Vmovetoolbar-white.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Vsepartoolbar-black.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Vsepartoolbar-blue.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Vsepartoolbar-darkgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Vsepartoolbar-lightgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/Vsepartoolbar-white.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/autohide-black.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/autohide-blue.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/autohide-darkgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/autohide-lightgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/autohide-white.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/background_freecad.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/background_freecad_dark.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/background_freecad_light.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/check-mark-black.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/check-mark-blue.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/check-mark-darkgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/check-mark-lightgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/check-mark-white.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/checkbox-Empty-black.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/checkbox-Empty-blue.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/checkbox-Empty-darkgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/checkbox-Empty-lightgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/checkbox-Empty-white.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/checkbox-checked-black.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/checkbox-checked-blue.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/checkbox-checked-darkgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/checkbox-checked-lightgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/checkbox-checked-white.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/checkbox-indeterminate-black.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/checkbox-indeterminate-blue.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/checkbox-indeterminate-darkgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/checkbox-indeterminate-lightgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/checkbox-indeterminate-white.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/close-black.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/close-blue.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/close-darkerred.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/close-darkgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/close-lightred.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/close-red.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/close-white.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/edithide-black.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/edithide-blue.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/edithide-darkgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/edithide-lightgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/edithide-white.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/editshow-black.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/editshow-blue.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/editshow-darkgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/editshow-lightgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/editshow-white.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/float-black.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/float-blue.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/float-darkgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/float-lightgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/float-white.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/indeterminate-mark-black.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/indeterminate-mark-blue.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/indeterminate-mark-darkgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/indeterminate-mark-lightgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/indeterminate-mark-white.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/mode-black.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/mode-blue.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/mode-darkgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/mode-lightgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/mode-white.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/more-black-lightgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/more-black.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/more-blue.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/more-darkgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/more-white.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/overlay-black.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/overlay-blue.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/overlay-lightgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/overlay-white.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/overlay_lighter.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/sizegrip-black.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/sizegrip-blue.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/sizegrip-darkgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/sizegrip-lightgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/sizegrip-white.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/splitter_horizontal-black.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/splitter_horizontal-blue.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/splitter_horizontal-darkgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/splitter_horizontal-lightgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/splitter_horizontal-white.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/splitter_vertical-black.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/splitter_vertical-blue.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/splitter_vertical-darkgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/splitter_vertical-lightgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/splitter_vertical-white.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/taskshow-black.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/taskshow-blue.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/taskshow-darkgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/taskshow-lightgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/taskshow-white.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/transparent-black.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/transparent-blue.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/transparent-darkgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/transparent-lightgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/transparent-white.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/transparent.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/undock-black-lightgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/undock-black.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/undock-blue.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/undock-darkgray.png"
    "/home/jarvis/Documents/freecad-source/src/Gui/Stylesheets/images_classic/undock-white.png"
    )
endif()

